// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk3125Pg1nAMtVCu4JVHY5pMHBZPT7SoM',
    appId: '1:15354620310:web:8969b0595036f66a80d5b7',
    messagingSenderId: '15354620310',
    projectId: 'vehicle-man',
    authDomain: 'vehicle-man.firebaseapp.com',
    storageBucket: 'vehicle-man.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeyV4iqHO2P_Fso26j3hDehQynG9g1Dqo',
    appId: '1:15354620310:android:edf916be9a09e80880d5b7',
    messagingSenderId: '15354620310',
    projectId: 'vehicle-man',
    storageBucket: 'vehicle-man.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCk3125Pg1nAMtVCu4JVHY5pMHBZPT7SoM',
    appId: '1:15354620310:web:2924082f2a6254e980d5b7',
    messagingSenderId: '15354620310',
    projectId: 'vehicle-man',
    authDomain: 'vehicle-man.firebaseapp.com',
    storageBucket: 'vehicle-man.firebasestorage.app',
  );
}
